In [1]:
import pandas as pd
from string import ascii_uppercase as alphabet
import pickle

In [2]:
todas_tablas = pd.read_html("https://en.wikipedia.org/wiki/2014_FIFA_World_Cup")

In [3]:
todas_tablas[11]

   Pos     Teamvte  Pld  W  D  L  GF  GA  GD  Pts              Qualification
0    1  Brazil (H)    3  2  1  0   7   2  +5    7  Advance to knockout stage
1    2      Mexico    3  2  1  0   4   1  +3    7  Advance to knockout stage
2    3     Croatia    3  1  0  2   6   6   0    3                        NaN
3    4    Cameroon    3  0  0  3   1   9  −8    0                        NaN

In [8]:
todas_tablas = pd.read_html("https://en.wikipedia.org/wiki/2014_FIFA_World_Cup")
dict_tablas = {}
for letra,i in zip(alphabet, range (11, 61, 7)):
    df = todas_tablas[i]
    df.rename(columns = {df.columns[1] : "Team"}, inplace = True)
    df.pop("Qualification")
    dict_tablas[f"Group {letra}"] = df

In [9]:
dict_tablas.keys()
dict_tablas["Group A"]

   Pos        Team  Pld  W  D  L  GF  GA  GD  Pts
0    1  Brazil (H)    3  2  1  0   7   2  +5    7
1    2      Mexico    3  2  1  0   4   1  +3    7
2    3     Croatia    3  1  0  2   6   6   0    3
3    4    Cameroon    3  0  0  3   1   9  −8    0

In [10]:
with open ("dict_table", "wb") as output:
    pickle.dump(dict_tablas, output)